### ISSUE TITLE
Gridea+GitHub Pages搭建个人博客，一步到位！ | Luminous

### ISSUE THREAD

**Issue by Luminous-ee** [Luminous-ee/luminous-ee.github.io#6]
https://luminous-ee.github.io/post/grideagithub-pages-da-jian-ge-ren-bo-ke-yi-bu-dao-wei/ 

 Hello Gridea

👏 欢迎使用 Gridea ！
✍️ Gridea 一个静态博客写作客户端。你可以用它来记录你的生活、心情、知识、笔记、创意... ...
Github
Gridea 主页
示例网站
特性👇
📝 你可以使用...

**Comment by Azad-sl** [comment]
请问评论必须登录GitHub吗？

**Comment by Luminous-ee** [comment]
Gitalk 是一个基于 GitHub Issue 和 Preact 开发的评论插件，它限制了只有 GitHub 用户才能登录评论。

**Comment by Luminous-ee** [comment]
> 请问评论必须登录GitHub吗？

Gitalk 是一个基于 GitHub Issue 和 Preact 开发的评论插件，它限制了只有 GitHub 用户才能登录评论。
